### ISSUE TITLE
Downloading Error In Permission Granted ...please help me sir🙏🙏🙏

### ISSUE THREAD

**Issue by emoboyfriend** [MindorksOpenSource/PRDownloader#186]
Downloading video in First Install state. Request and granted write external storage permission at click time of the download button and downloading once a video. And then permission is granted, second and more video is not downloading. 

Utils.java  
`
import android.content.Context;
import android.os.Environment;

import androidx.core.content.ContextCompat;

import java.io.File;
import java.net.URI;
import java.util.Locale;

public final class Utils {

    private Utils() {

    }

    public static String getRootDirPath(Context context) {

        String mBaseFolderPath = android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DOWNLOADS)+ File.separator + "App Name" + File.separator ;
        if (!new File(mBaseFolderPath).exists()) {
            new File(mBaseFolderPath).mkdir();
        }
        return mBaseFolderPath;
    }

    public static String getProgressDisplayLine(long currentBytes, long totalBytes) {
        return getBytesToMBString(currentBytes) + "/" + getBytesToMBString(totalBytes);
    }

    private static String getBytesToMBString(long bytes) {
        return String.format(Locale.ENGLISH, "%.2fMb", bytes / (1024.00 * 1024.00));
    }
}
`

DownloadButton Click Activity
` private void downloadFile(XModel xModel) {
        current_Xmodel = xModel;

        if (checkPermissions()) {
            String url = current_Xmodel.getUrl();
            String path = Utils.getRootDirPath(this);
            String file_name = videotitle + ".mp4";
            MyDownloader myDownloader = new MyDownloader(url, path, file_name, MoviePlay.this, xModel, title);
            myDownloader.ratingDialog();
          
        }
    }

    private boolean checkPermissions() {
        int storage = ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE);

        final List<String> listPermissionsNeeded = new ArrayList<>();
        if (storage != PackageManager.PERMISSION_GRANTED) {
            listPermissionsNeeded.add(Manifest.permission.WRITE_EXTERNAL_STORAGE);
        }

        if (!listPermissionsNeeded.isEmpty()) {
            ActivityCompat.requestPermissions(this, listPermissionsNeeded.toArray(new String[listPermissionsNeeded.size()]), 1000);
            return  false;
        }

        return true;
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode==1000){
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {

                    downloadFile(current_Xmodel);
            } else {
                checkPermissions();
                Toast.makeText(this, "You need to allow this permission!", Toast.LENGTH_SHORT).show();
            }
            return;
        }
    }

`

MyDownloader.java
`import android.annotation.SuppressLint;
import android.app.Dialog;
import android.content.ActivityNotFoundException;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.net.Uri;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;
import com.downloader.*;
import com.htetznaing.lowcostvideo.Model.XModel;
import com.linnmal.app.DownloadedVideos;
import com.linnmal.app.MoviePlay;
import com.linnmal.app.R;

import java.lang.Error;
import java.security.SecureRandom;

public class MyDownloader {

    private String url,dirPath,fileName,title;
    private Context context;
    XModel current_Xmodel = null;

    TextView file_downloaded_path, file_name, downloading_percent;
    ProgressBar progressBar;
    Button btnStart, btnCancel;
    int downloadID;

    public MyDownloader(String url,String dirPath, String fileName,Context context,XModel current_Xmodel,String title) {
        this.url = url;
        this.dirPath=dirPath;
        this.fileName = fileName;
        this.context=context;
        this.current_Xmodel=current_Xmodel;
        this.title=title;
    }

    public void ratingDialog() {
        final Dialog dialog1 = new Dialog(context);
        dialog1.getWindow().requestFeature(Window.FEATURE_NO_TITLE);
        dialog1.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN);
        dialog1.setContentView(R.layout.download_dialog);
        dialog1.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
        dialog1.setCancelable(false);

        // finding textview by its id
        file_downloaded_path = dialog1.findViewById(R.id.txt_url);

        // finding textview by its id
        file_name =dialog1.findViewById(R.id.file_name);

        // finding progressbar by its id
        progressBar = dialog1.findViewById(R.id.progress_horizontal);

        // finding textview by its id
        downloading_percent = dialog1.findViewById(R.id.downloading_percentage);

        // finding button by its id
        btnStart = dialog1.findViewById(R.id.btn_start);

        // finding button by its id
        btnCancel = dialog1.findViewById(R.id.btn_stop);

        btnStart.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                // checks if the process is already running
                if (Status.RUNNING == PRDownloader.getStatus(downloadID)) {
                    // pauses the download if
                    // user click on pause button
                    PRDownloader.pause(downloadID);
                    return;
                }

                // enabling the start button
                btnStart.setEnabled(false);

                // checks if the status is paused
                if (Status.PAUSED == PRDownloader.getStatus(downloadID)) {
                    // resume the download if download is paused
                    PRDownloader.resume(downloadID);
                    return;
                }

                // setting the file name
                file_name.setText(fileName+"  အားဒေါင်းလော့ဆွဲယူနေပါသည်။ဒေါင်းလော့ပြည့်အောင် ခေတ္တစောင့်ပေးပါ။ Appမှ ထွက်လိုက်ပါက ဒေါင်းလော့ဆွဲခြင်းမအောင်မြင်နိုင်ပါ။");

                // making the download request
                downloadID = PRDownloader.download(url, dirPath, fileName)
                        .build()
                        .setOnStartOrResumeListener(new OnStartOrResumeListener() {
                            @SuppressLint("SetTextI18n")
                            @Override
                            public void onStartOrResume() {
                                progressBar.setIndeterminate(false);
                                // enables the start button
                                btnStart.setEnabled(true);
                                // setting the text of start button to pause
                                btnStart.setText("Pause");
                                // enabling the stop button
                                btnCancel.setEnabled(true);
                                Toast.makeText(context, "Downloading started", Toast.LENGTH_SHORT).show();
                            }
                        })
                        .setOnPauseListener(new OnPauseListener() {
                            @Override
                            public void onPause() {
                                // setting the text of start button to resume
                                // when the download is in paused state
                                btnStart.setText("Resume");
                                Toast.makeText(context, "Downloading Paused", Toast.LENGTH_SHORT).show();
                            }
                        })
                        .setOnCancelListener(new OnCancelListener() {
                            @Override
                            public void onCancel() {
                                // resetting the downloadId when
                                // the download is cancelled
                                downloadID = 0;
                                // setting the text of start button to start
                                btnStart.setText("Start");
                                // disabling the cancel button
                                btnCancel.setEnabled(false);
                                // resetting the progress bar
                                progressBar.setProgress(0);
                                // restting the download precent
                                downloading_percent.setText("");
                                progressBar.setIndeterminate(false);
                                Toast.makeText(context, "Downloading Cancelled", Toast.LENGTH_SHORT).show();
                            }
                        })
                        .setOnProgressListener(new OnProgressListener() {
                            @Override
                            public void onProgress(Progress progress) {
                                // getting the progress of download
                                long progressPer = progress.currentBytes * 100 / progress.totalBytes;
                                // setting the progress to progressbar
                                progressBar.setProgress((int) progressPer);
                                // setting the download percent
                                downloading_percent.setText(Utils.getProgressDisplayLine(progress.currentBytes, progress.totalBytes));
                                progressBar.setIndeterminate(false);
                            }
                        })
                        .start(new OnDownloadListener() {

                            @Override
                            public void onDownloadComplete() {
                                // disabling the start button
                                btnStart.setEnabled(false);
                                // disabling the cancel button
                               // btnCancel.setEnabled(false);
                                // setting the text completed to start button
                                btnStart.setText("Completed");
                                btnCancel.setText("Open");
                                // will show the path after the file is downloaded
                                file_downloaded_path.setText("File stored at : " + dirPath+fileName);
                                Toast.makeText(context, "Downloading Completed", Toast.LENGTH_SHORT).show();
                            }

                            @Override
                            public void onError(com.downloader.Error error) {
                                btnStart.setText("Start");
                                // resetting the download percentage
                                downloading_percent.setText("0");
                                file_downloaded_path.setText("ယခုVideoအား Adm Downloader ဖြင့်သာဒေါင်းယူနိုင်ပါမည်။");
                                // resetting the progressbar
                                progressBar.setProgress(0);
                                // resetting the downloadID
                                downloadID = 0;
                                // enabling the start button
                                btnStart.setEnabled(true);
                                // disabling the cancel button
                                btnCancel.setText("ADM Downloader");
                               // btnCancel.setEnabled(false);
                                progressBar.setIndeterminate(false);
                                Toast.makeText(context, "Error Occurred", Toast.LENGTH_SHORT).show();
                            }

                        });
            }

        });
        btnCancel.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                // cancels the download
                if(btnCancel.getText().equals("Open")){
                    Intent i=new Intent(context, DownloadedVideos.class);
                    context.startActivity(i);
                    dialog1.dismiss();
                }
                else if(btnCancel.getText().equals("ADM Downloader")) {
                    PRDownloader.cancel(downloadID);
                    dialog1.dismiss();
                    downloadWithADM(current_Xmodel);

                }
                else
                 {
                    PRDownloader.cancel(downloadID);
                     dialog1.dismiss();
                    btnStart.setText("Start");
                }

            }

        });
        dialog1.show();

    }
    public boolean appInstalledOrNot2(String str) {
        try {
            context.getPackageManager().getPackageInfo(str, PackageManager.GET_ACTIVITIES);
            return true;
        } catch (PackageManager.NameNotFoundException e) {
            return false;
        }
    }
    public void downloadWithADM(XModel xModel) {
        boolean appInstalledOrNot = appInstalledOrNot2( "com.dv.adm");
        boolean appInstalledOrNot2 = appInstalledOrNot2("com.dv.adm.pay");
        boolean appInstalledOrNot3 = appInstalledOrNot2( "com.dv.adm.old");
        String str3;
        if (appInstalledOrNot || appInstalledOrNot2 || appInstalledOrNot3) {
            if (appInstalledOrNot2) {
                str3 = "com.dv.adm.pay";
            } else if (appInstalledOrNot) {
                str3 = "com.dv.adm";
            } else {
                str3 = "com.dv.adm.old";
            }

            try {
                Intent intent = new Intent(Intent.ACTION_VIEW);
                intent.setDataAndType(Uri.parse(xModel.getUrl()), "application/x-mpegURL");
                intent.setPackage(str3);
                intent.hasExtra(title);
                if (xModel.getCookie()!=null) {
                    intent.putExtra("Cookie", xModel.getCookie());
                    intent.putExtra("Cookies", xModel.getCookie());
                    intent.putExtra("cookie", xModel.getCookie());
                    intent.putExtra("cookies", xModel.getCookie());
                }

                context.startActivity(intent);
                return;
            } catch (Exception e) {
                return;
            }
        }
        str3 = "com.dv.adm";
        try {
            context.startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("market://details?id="+str3)));
        } catch (ActivityNotFoundException e2) {
            context.startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id="+str3)));
        }
    }

}
`

download_dialog.xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              android:orientation="vertical"
              android:layout_width="300dp"
              android:layout_height="300dp"
              android:gravity="center"
              android:padding="5dp"
              android:background="@drawable/alert_dialog_download">

    <TextView
            android:id="@+id/file_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/click_on_start_button_to_start_downloading"
            android:textSize="10sp"
            android:textColor="@color/colorPrimary"
            android:textStyle="bold" />

    
    <ProgressBar
            android:id="@+id/progress_horizontal"
            style="@style/Widget.AppCompat.ProgressBar.Horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="4dp"
            android:layout_marginRight="4dp"
            tools:ignore="UnusedAttribute" />

    
    <TextView
            android:id="@+id/downloading_percentage"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:textAlignment="center"
            android:textSize="12sp"
            android:textColor="#2B2A2A"
            android:textStyle="bold" />

    
    <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:orientation="horizontal"
            android:padding="10dp">

        
        <Button
                android:textColor="#ffffff"
                android:id="@+id/btn_start"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@drawable/button_bg"
                android:text="@string/start" />

        
        <Button
                android:layout_marginLeft="20dp"
                android:textColor="#ffffff"
                android:id="@+id/btn_stop"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@drawable/button_bg"
                android:text="@string/stop" />
    </LinearLayout>

    <TextView
            android:textColor="#2B2A2A"
            android:id="@+id/txt_url"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:textSize="15sp"
            android:textStyle="bold" />

    </LinearLayout>`

**Comment by emoboyfriend** [comment]
Error Message

`2021-08-13 00:47:49.143 17248-17248/? E/com.linnmal.ap: Unknown bits set in runtime_flags: 0x28000
2021-08-13 00:47:49.143 17248-17248/? E/com.linnmal.ap: Unknown bits set in runtime_flags: 0x28000
2021-08-13 00:47:49.905 17248-17283/com.linnmal.app E/Perf: Fail to get file list com.linnmal.app
2021-08-13 00:47:49.905 17248-17283/com.linnmal.app E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-08-13 00:47:49.906 17248-17283/com.linnmal.app E/Perf: Fail to get file list com.linnmal.app
2021-08-13 00:47:49.906 17248-17283/com.linnmal.app E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-08-13 00:48:26.106 17248-17248/com.linnmal.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.linnmal.app, PID: 17248
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8384)
        at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:4203)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:949)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:949)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:949)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:949)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:949)
        at android.view.View.setFlags(View.java:15227)
        at android.view.View.setEnabled(View.java:10897)
        at android.widget.TextView.setEnabled(TextView.java:2216)
        at com.linnmal.app.Utils.MyDownloader$1$5.onStartOrResume(MyDownloader.java:114)
        at com.downloader.request.DownloadRequest$3.run(DownloadRequest.java:274)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:221)
        at android.app.ActivityThread.main(ActivityThread.java:7542)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`
